export const TEST_IDS = {
  TEST_ID_SHOP_NAME: 'TEST_ID_SHOP_NAME',
  TEST_ID_SHOP_DESCRIPTION: 'TEST_ID_SHOP_DESCRIPTION',
  TEST_ID_IMAGE_SHOP: 'TEST_ID_IMAGE_SHOP',
  MAP_BUTTON_TOUCHABLE: 'MAP_BUTTON_TOUCHABLE',
};
